--import ssfamilles

Insert into SSFAMILLE (ID_SSFAMILLE,NOM_SSFAMILLE) values ('1','Caoutchouc');
Insert into SSFAMILLE (ID_SSFAMILLE,NOM_SSFAMILLE) values ('2','Loisir');
Insert into SSFAMILLE (ID_SSFAMILLE,NOM_SSFAMILLE) values ('3','Sécurité');
Insert into SSFAMILLE (ID_SSFAMILLE,NOM_SSFAMILLE) values ('4','UV');

-- import familles

Insert into FAMILLE (ID_FAMILLE,NOM_FAMILLE) values ('1','Elastique Loom');
Insert into FAMILLE (ID_FAMILLE,NOM_FAMILLE) values ('2','Elastique de sécurité');
Insert into FAMILLE (ID_FAMILLE,NOM_FAMILLE) values ('3','Elastique crochet');
Insert into FAMILLE (ID_FAMILLE,NOM_FAMILLE) values ('4','Elastique bracelet');

--import marques
Insert into FABRICANT (ID_FABRICANT,NOM_FABRICANT) values ('1','CALEOPACK');
Insert into FABRICANT (ID_FABRICANT,NOM_FABRICANT) values ('2','EUROPAGES');
Insert into FABRICANT (ID_FABRICANT,NOM_FABRICANT) values ('3','LOOM');
Insert into FABRICANT (ID_FABRICANT,NOM_FABRICANT) values ('4','MULTIFIBRE');
Insert into FABRICANT (ID_FABRICANT,NOM_FABRICANT) values ('5','SANDORF');
Insert into FABRICANT (ID_FABRICANT,NOM_FABRICANT) values ('6','STN');

-- import couleurs
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (1,'Abricot','E6','7E','30',230,126,48,'#E67E30');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (2,'Absinthe','7F','DD','4C',127,221,76,'#7FDD4C');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (3,'Acajou','88','42','1D',136,66,29,'#88421D');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (4,'Aigue-marine','79','F8','F8',121,248,248,'#79F8F8');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (5,'Aile de corbeau (cheveux)','0','0','0',0,0,0,'#000');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (6,'Albâtre','FE','FE','FE',254,254,254,'#FEFEFE');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (7,'Alezan (chevaux)','A7','67','26',167,103,38,'#A76726');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (8,'Amande','82','C4','6C',130,196,108,'#82C46C');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (9,'Amarante','91','28','3B',145,40,59,'#91283B');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (10,'Ambre jaune','F0','C3','0',240,195,0,'#F0C30');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (11,'Ambre rouge','AD','39','0E',173,57,14,'#AD390E');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (12,'Améthyste','88','4D','A7',136,77,167,'#884DA7');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (13,'Anthracite','30','30','30',48,48,48,'#303030');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (14,'Aquilain (chevaux)','AD','4F','9',173,79,9,'#AD4F9');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (15,'Ardoise','5A','5E','6B',90,94,107,'#5A5E6B');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (16,'Argent','CE','CE','CE',206,206,206,'#CECECE');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (17,'Argent (héraldique)4','FF','FF','FF',255,255,255,'#FFFFFF');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (18,'Argile','EF','EF','EF',239,239,239,'#EFEFEF');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (19,'Asperge','7B','A0','5B',123,160,91,'#7BA05B');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (20,'Aubergine','37','0','28',55,0,40,'#37028');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (21,'Auburn (cheveux)','9D','3E','0C',157,62,12,'#9D3E0C');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (22,'Aurore','FF','CB','60',255,203,96,'#FFCB60');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (23,'Avocat','56','82','3',86,130,3,'#56823');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (24,'Azur','0','7F','FF',0,127,255,'#07FFF');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (25,'Azur (héraldique)','1E','7F','CB',30,127,203,'#1E7FCB');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (26,'Azur brume','F0','FF','FF',240,255,255,'#F0FFFF');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (27,'Azur clair','74','D0','F1',116,208,241,'#74D0F1');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (28,'Azurin','A9','EA','FE',169,234,254,'#A9EAFE');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (29,'Baillet (chevaux vieilli)','AE','64','2D',174,100,45,'#AE642D');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (30,'Banane','D1','B6','6',209,182,6,'#D1B66');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (31,'Basané (teint)','8B','6C','42',139,108,66,'#8B6C42');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (32,'Beige','C8','AD','7F',200,173,127,'#C8AD7F');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (33,'Beige clair','F5','F5','DC',245,245,220,'#F5F5DC');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (34,'Beigeasse (péjoratif)','AF','A7','7B',175,167,123,'#AFA77B');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (35,'Beurre','F0','E3','6B',240,227,107,'#F0E36B');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (36,'Beurre frais','FF','F4','8D',255,244,141,'#FFF48D');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (37,'Bis','76','6F','64',118,111,100,'#766F64');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (38,'Bis (héraldique)','F1','E2','BE',241,226,190,'#F1E2BE');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (39,'Bisque','FF','E4','C4',255,228,196,'#FFE4C4');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (40,'Bistre','85','6D','4D',133,109,77,'#856D4D');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (41,'Bitume (pigment)','4E','3D','28',78,61,40,'#4E3D28');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (42,'Blanc','FF','FF','FF',255,255,255,'#FFFFFF');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (43,'Blanc cassé','FE','FE','E2',254,254,226,'#FEFEE2');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (44,'Blanc d''argent (pigment) ou de plomb','FE','FE','FE',254,254,254,'#FEFEFE');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (45,'Blanc d''Espagne (pigment)','FE','FD','F0',254,253,240,'#FEFDF0');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (46,'Blanc de lait','FB','FC','FA',251,252,250,'#FBFCFA');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (47,'Blanc de Meudon ou de Troyes (pigment)','FE','FD','F0',254,253,240,'#FEFDF0');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (48,'Blanc de zinc (pigment)','F6','FE','FE',246,254,254,'#F6FEFE');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (49,'Blanc lunaire','F4','FE','FE',244,254,254,'#F4FEFE');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (50,'Blé','E8','D6','30',232,214,48,'#E8D630');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (51,'Bleu acier','3A','8E','BA',58,142,186,'#3A8EBA');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (52,'Bleu barbeau ou bleuet','54','72','AE',84,114,174,'#5472AE');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (53,'Bleu canard','4','8B','9A',4,139,154,'#48B9A');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (54,'Bleu céleste','26','C4','EC',38,196,236,'#26C4EC');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (55,'Bleu charrette','8E','A2','C6',142,162,198,'#8EA2C6');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (56,'Bleu ciel','77','B5','FE',119,181,254,'#77B5FE');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (57,'Bleu de cobalt (pigment)','22','42','7C',34,66,124,'#22427C');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (58,'Bleu de minuit','0','33','66',0,51,102,'#03366');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (59,'Bleu de Prusse (pigment), de Berlin ou bleu hussard','24','44','5C',36,68,92,'#24445C');
--Ligne 60
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (60,'Bleu des mers du sud','0','CC','CB',0,204,203,'#0CCCB');
--Ligne 61
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (61,'Bleu dragée','DF','F2','FF',223,242,255,'#DFF2FF');
--Ligne 62
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (62,'Bleu électrique','2C','75','FF',44,117,255,'#2C75FF');
--Ligne 63
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (63,'Bleu fumée','BB','D2','E1',187,210,225,'#BBD2E1');
--Ligne 64
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (64,'Bleu givré','80','D0','D0',128,208,208,'#80D0D0');
--Ligne 65
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (65,'Bleu guède (pigment)','56','73','9A',86,115,154,'#56739A');
--Ligne 66
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (66,'Bleu Klein','0','2F','A7',0,47,167,'#02FA7');
--Ligne 67
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (67,'Bleu Majorelle','60','50','DC',96,80,220,'#6050DC');
--Ligne 68
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (68,'Bleu nuit','0F','5','6B',15,5,107,'#0F56B');
--Ligne 69
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (69,'Bleu outremer','1B','1','9B',27,1,155,'#1B19B');
--Ligne 70
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (70,'Bleu paon','6','77','90',6,119,144,'#67790');
--Ligne 71
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (71,'Bleu Persan','66','0','FF',102,0,255,'#660FF');
--Ligne 72
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (72,'Bleu pétrole','1D','48','51',29,72,81,'#1D4851');
--Ligne 73
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (73,'Bleu','0','80','FF',0,128,255,'#080FF');
--Ligne 74
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (74,'Bleu roi ou de France','31','8C','E7',49,140,231,'#318CE7');
--Ligne 75
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (75,'Bleu turquin','42','5B','8A',66,91,138,'#425B8A');
--Ligne 76
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (76,'Blond vénitien (cheveux)','E7','A8','54',231,168,84,'#E7A854');
--Ligne 77
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (77,'Blond (cheveux)','E2','BC','74',226,188,116,'#E2BC74');
--Ligne 78
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (78,'Bordeaux','6D','7','1A',109,7,26,'#6D71A');
--Ligne 79
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (79,'Bourgogne','6B','0D','0D',107,13,13,'#6B0D0D');
--Ligne 80
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (80,'Bouton d''or','FC','DC','12',252,220,18,'#FCDC12');
--Ligne 81
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (81,'Brique','84','2E','1B',132,46,27,'#842E1B');
--Ligne 82
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (82,'Bronze','61','4E','1A',97,78,26,'#614E1A');
--Ligne 83
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (83,'Brou de noix','3F','22','4',63,34,4,'#3F224');
--Ligne 84
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (84,'Brun (cheveux)','5B','3C','11',91,60,17,'#5B3C11');
--Ligne 85
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (85,'Brun clair (cheveux)','CD','85','3F',205,133,63,'#CD853F');
--Ligne 86
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (86,'Bureau','6B','57','31',107,87,49,'#6B5731');
--Ligne 87
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (87,'Caca d''oie','CD','CD','0D',205,205,13,'#CDCD0D');
--Ligne 88
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (88,'Cacao','61','4B','3A',97,75,58,'#614B3A');
--Ligne 89
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (89,'Cachou (pigments)','2F','1B','0C',47,27,12,'#2F1B0C');
--Ligne 90
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (90,'Cæruléum','35','7A','B7',53,122,183,'#357AB7');
--Ligne 91
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (91,'Café','46','2E','1',70,46,1,'#462E1');
--Ligne 92
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (92,'Café au lait','78','5E','2F',120,94,47,'#785E2F');
--Ligne 93
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (93,'Cannelle','7E','58','35',126,88,53,'#7E5835');
--Ligne 94
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (94,'Capucine','FF','5E','4D',255,94,77,'#FF5E4D');
--Ligne 95
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (95,'Caramel (pigments)','7E','33','0',126,51,0,'#7E330');
--Ligne 96
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (96,'Carmin (pigment)','96','0','18',150,0,24,'#96018');
--Ligne 97
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (97,'Carotte','F4','66','1B',244,102,27,'#F4661B');
--Ligne 98
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (98,'Cerise','DE','31','63',222,49,99,'#DE3163');
--Ligne 99
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (99,'Cerise Hollywood','F4','0','A1',244,0,161,'#F40A1');
--Ligne 100
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (100,'Cerise profonde','DA','32','87',218,50,135,'#DA3287');
--Ligne 101
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (101,'Cerise rose','EC','3B','83',236,79,131,'#EC3B83');
--Ligne 102
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (102,'Céruse (pigment)','FE','FE','FE',254,254,254,'#FEFEFE');
--Ligne 103
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (103,'Chair','FE','C3','AC',254,195,172,'#FEC3AC');
--Ligne 104
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (104,'Chamois','D0','C0','7A',208,192,122,'#D0C07A');
--Ligne 105
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (105,'Chartreuse','7F','FF','0',127,255,0,'#7FFF0');
--Ligne 106
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (106,'Châtaigne','80','6D','5A',128,109,90,'#806D5A');
--Ligne 107
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (107,'Châtain (cheveux)','8B','6C','42',139,108,66,'#8B6C42');
--Ligne 108
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (108,'Chaudron','85','53','0F',133,83,15,'#85530F');
--Ligne 109
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (109,'Chocolat','5A','3A','22',90,58,34,'#5A3A22');
--Ligne 110
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (110,'Cinabre (pigment)','DB','17','2',219,23,2,'#DB172');
--Ligne 111
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (111,'Citron','F7','FF','3C',247,255,60,'#F7FF3C');
--Ligne 112
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (112,'Citrouille','DF','6D','14',223,109,20,'#DF6D14');
--Ligne 113
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (113,'Colombin (vieilli)','6A','45','5D',106,69,93,'#6A455D');
--Ligne 114
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (114,'Coquelicot','C6','8','0',198,8,0,'#C680');
--Ligne 115
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (115,'Coquille d''œuf','FD','E9','E0',253,233,224,'#FDE9E0');
--Ligne 116
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (116,'Corail','E7','3E','1',231,62,1,'#E73E1');
--Ligne 117
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (117,'Cramoisi','DC','14','3C',220,20,60,'#DC143C');
--Ligne 118
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (118,'Crème','FD','F1','B8',253,241,184,'#FDF1B8');
--Ligne 119
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (119,'Cuisse de nymphe','FE','E7','F0',254,231,240,'#FEE7F0');
--Ligne 120
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (120,'Cuisse de nymphe émue','FF','69','B4',255,105,180,'#FF69B4');
--Ligne 121
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (121,'Cuivre','B3','67','0',179,103,0,'#B3670');
--Ligne 122
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (122,'Cyan','2B','FA','FA',43,250,250,'#2BFAFA');
--Ligne 123
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (123,'Denim','15','60','BD',21,96,189,'#1560BD');
--Ligne 124
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (124,'Ébène','0','0','0',0,0,0,'#000');
--Ligne 125
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (125,'Écarlate','ED','0','0',237,0,0,'#ED00');
--Ligne 126
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (126,'Écru','FE','FE','E0',254,254,224,'#FEFEE0');
--Ligne 127
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (127,'Émeraude','1','D7','58',1,215,88,'#1D758');
--Ligne 128
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (128,'Étain','ED','ED','ED',237,237,237,'#EDEDED');
--Ligne 129
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (129,'Fauve','AD','4F','9',173,79,9,'#AD4F9');
--Ligne 130
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (130,'Feu','FF','49','1',255,73,1,'#FF491');
--Ligne 131
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (131,'Feuille morte','99','51','2B',153,81,43,'#99512B');
--Ligne 132
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (132,'Flave','E6','E6','97',230,230,151,'#E6E697');
--Ligne 133
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (133,'Fraise','BF','30','30',191,48,48,'#BF3030');
--Ligne 134
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (134,'Fraise écrasée','A4','24','24',164,36,36,'#A42424');
--Ligne 135
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (135,'Framboise','C7','2C','48',199,44,72,'#C72C48');
--Ligne 136
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (136,'Framboise rose','E2','50','98',226,80,152,'#E25098');
--Ligne 137
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (137,'Fuchsia','FD','3F','92',253,63,146,'#FD3F92');
--Ligne 138
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (138,'Garance (pigment)','EE','10','10',238,16,16,'#EE1010');
--Ligne 139
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (139,'Glauque','64','9B','88',100,155,136,'#649B88');
--Ligne 140
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (140,'Glycine','C9','A0','DC',201,160,220,'#C9A0DC');
--Ligne 141
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (141,'Grège','BB','AE','98',187,174,152,'#BBAE98');
--Ligne 142
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (142,'Grenadine','E9','38','3F',233,56,63,'#E9383F');
--Ligne 143
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (143,'Grenat','6E','0B','14',110,11,20,'#6E0B14');
--Ligne 144
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (144,'Gris','60','60','60',96,96,96,'#606060');
--Ligne 145
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (145,'Gris acier','AF','AF','AF',175,175,175,'#AFAFAF');
--Ligne 146
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (146,'Gris de lin','D2','CA','EC',210,202,236,'#D2CAEC');
--Ligne 147
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (147,'Gris de Payne (mélange de pigments)','67','71','79',103,113,121,'#677179');
--Ligne 148
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (148,'Gris fer','7F','7F','7F',127,127,127,'#7F7F7F');
--Ligne 149
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (149,'Gris perle','CE','CE','CE',206,206,206,'#CECECE');
--Ligne 150
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (150,'Groseille','CF','0A','1D',207,10,29,'#CF0A1D');
--Ligne 151
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (151,'Gueules (héraldique)','E2','13','13',226,19,19,'#E21313');
--Ligne 152
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (152,'Héliotrope','DF','73','FF',223,115,255,'#DF73FF');
--Ligne 153
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (153,'Incarnadin','FE','96','A0',254,150,160,'#FE96A0');
--Ligne 154
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (154,'Incarnat','FF','6F','7D',255,111,125,'#FF6F7D');
--Ligne 155
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (155,'Indigo chaud','79','1C','F8',121,28,248,'#791CF8');
--Ligne 156
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (156,'Indigo du web','4B','0','82',75,0,130,'#4B082');
--Ligne 157
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (157,'Indigo électrique','6F','0','FF',111,0,255,'#6F0FF');
--Ligne 158
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (158,'Indigo (teinture)','2E','0','6C',46,0,108,'#2E06C');
--Ligne 159
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (159,'Isabelle (chevaux)','78','5E','2F',120,94,47,'#785E2F');
--Ligne 160
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (160,'Ivoire','FF','FF','D4',255,255,212,'#FFFFD4');
--Ligne 161
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (161,'Jais','0','0','0',0,0,0,'#000');
--Ligne 162
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (162,'Jaune de cobalt ou auréolin (pigment)','FD','EE','0',253,238,0,'#FDEE0');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (163,'Jaune bouton d’or','F6','DC','12',246,220,18,'#F6DC12');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (164,'Jaune canari','E7','F0','0D',231,240,13,'#E7F00D');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (165,'Jaune chartreuse','DF','FF','0',223,255,0,'#DFFF0');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (166,'Jaune d''or','EF','D8','7',239,216,7,'#EFD87');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (167,'Jaune de Mars (pigment)','EE','D1','53',238,209,83,'#EED153');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (168,'Jaune de Naples (pigment)','FF','F0','BC',255,240,188,'#FFF0BC');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (169,'Jaune impérial','FF','E4','36',255,228,54,'#FFE436');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (170,'Jaune mimosa','FE','F8','6C',254,248,108,'#FEF86C');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (171,'Kaki','94','81','2B',148,129,43,'#94812B');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (172,'Lapis-lazuli','26','61','9C',38,97,156,'#26619C');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (173,'Lavallière (reliure)','8F','59','22',143,89,34,'#8F5922');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (174,'Lavande','96','83','EC',150,131,236,'#9683EC');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (175,'Lie de vin','AC','1E','44',172,30,68,'#AC1E44');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (176,'Lilas','B6','66','D2',182,102,210,'#B666D2');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (177,'Lin','FA','F0','E6',250,240,230,'#FAF0E6');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (178,'Magenta fuchsia (encre)','DB','0','73',219,0,115,'#DB073');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (179,'Magenta','FF','0','FF',255,0,255,'#FF0FF');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (180,'Magenta foncé, primaire en synthèse soustractive','80','0','80',128,0,128,'#80080');
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (181,'Maïs','FF','DE','75',255,222,117,'#FFDE75');
--Ligne 182
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (182,'Malachite','1F','A0','55',31,160,85,'#1FA055');
--Ligne 183
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (183,'Mandarine','FE','A3','47',254,163,71,'#FEA347');
--Ligne 184
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (184,'Marine','3','22','4C',3,34,76,'#3224C');
--Ligne 185
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (185,'Marron','58','29','0',88,41,0,'#58290');
--Ligne 186
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (186,'Mastic','B3','B1','91',179,177,145,'#B3B191');
--Ligne 187
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (187,'Mauve (couleur)','D4','73','D4',150,85,120,'#D473D4');
--Ligne 188
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (188,'Melon','DE','98','16',222,152,22,'#DE9816');
--Ligne 189
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (189,'Menthe','16','B8','4E',22,184,78,'#16B84E');
--Ligne 190
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (190,'Menthe à l''eau','54','F9','8D',84,249,141,'#54F98D');
--Ligne 191
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (191,'Mordoré','87','59','1A',135,89,26,'#87591A');
--Ligne 192
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (192,'Moutarde','C7','CF','0',199,207,0,'#C7CF0');
--Ligne 193
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (193,'Nacarat','FC','5D','5D',252,93,93,'#FC5D5D');
--Ligne 194
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (194,'Nankin','F7','E2','69',247,226,105,'#F7E269');
--Ligne 195
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (195,'Neige','FE','FE','FE',254,254,254,'#FEFEFE');
--Ligne 196
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (196,'Noir','0','0','0',0,0,0,'#000');
--Ligne 197
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (197,'Noir animal (pigment)','0','0','0',0,0,0,'#000');
--Ligne 198
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (198,'Noir d''aniline (pigment)','12','0D','16',18,13,22,'#120D16');
--Ligne 199
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (199,'Noir d''encre','0','0','0',0,0,0,'#000');
--Ligne 200
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (200,'Noir d''ivoire (pigment)','0','0','0',0,0,0,'#000');
--Ligne 201
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (201,'Noir de carbone (pigment)','13','0E','0A',19,14,10,'#130E0A');
--Ligne 202
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (202,'Noir de fumée (pigment)','13','0E','0A',19,14,10,'#130E0A');
--Ligne 203
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (203,'Noir de jais','0','0','0',0,0,0,'#000');
--Ligne 204
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (204,'Noisette','95','56','28',149,86,40,'#955628');
--Ligne 205
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (205,'Ocre jaune (pigment)','DF','AF','2C',223,175,44,'#DFAF2C');
--Ligne 206
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (206,'Ocre rouge (pigment)','DD','98','5C',221,152,92,'#DD985C');
--Ligne 207
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (207,'Olive','70','8D','23',112,141,35,'#708D23');
--Ligne 208
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (208,'Opale','66','CC','CC',102,204,204,'#66CCCC');
--Ligne 209
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (209,'Or','FF','D7','0',255,215,0,'#FFD70');
--Ligne 210
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (210,'Orange','FF','7F','0',255,127,0,'#FF7F0');
--Ligne 211
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (211,'Orange brûlé','CC','55','0',204,85,0,'#CC550');
--Ligne 212
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (212,'Orchidée','DA','70','D6',218,112,214,'#DA70D6');
--Ligne 213
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (213,'Orpiment (pigment)','FC','D2','1C',252,210,28,'#FCD21C');
--Ligne 214
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (214,'Orpin de Perse','FC','D2','1C',252,210,28,'#FCD21C');
--Ligne 215
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (215,'Paille','FE','E3','47',254,227,71,'#FEE347');
--Ligne 216
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (216,'Parme','CF','A0','E9',207,160,233,'#CFA0E9');
--Ligne 217
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (217,'Pastel (pigment)','56','73','9A',86,115,154,'#56739A');
--Ligne 218
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (218,'Pelure d''oignon (œnologie)','D5','84','90',213,132,144,'#D58490');
--Ligne 219
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (219,'Pervenche','CC','CC','FF',204,204,255,'#CCCCFF');
--Ligne 220
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (220,'Pistache','BE','F5','74',190,245,116,'#BEF574');
--Ligne 221
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (221,'Poil de chameau','B6','78','23',182,120,35,'#B67823');
--Ligne 222
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (222,'Ponceau','C6','8','0',198,8,0,'#C680');
--Ligne 223
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (223,'Pourpre (héraldique)','9E','0E','40',158,14,64,'#9E0E40');
--Ligne 224
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (224,'Prasin','4C','A6','6B',76,166,107,'#4CA66B');
--Ligne 225
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (225,'Prune','81','14','53',129,20,83,'#811453');
--Ligne 226
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (226,'Puce','4E','16','9',78,22,9,'#4E169');
--Ligne 227
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (227,'Queue-de-renard','91','28','3B',145,40,59,'#91283B');
--Ligne 228
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (228,'Rose','FD','6C','9E',253,108,158,'#FD6C9E');
--Ligne 229
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (229,'Rose bonbon','F9','42','9E',249,66,158,'#F9429E');
--Ligne 230
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (230,'Rose dragée','FE','BF','D2',254,191,210,'#FEBFD2');
--Ligne 231
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (231,'Rose du web','FF','C0','CB',255,192,203,'#FFC0CB');
--Ligne 232
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (232,'Rose Mountbatten','99','7A','8D',153,122,141,'#997A8D');
--Ligne 233
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (233,'Rose Persan vif','FE','28','A2',254,40,162,'#FE28A2');
--Ligne 234
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (234,'Rose razzle dazzle','EE','D5','D2',238,213,210,'#EED5D2');
--Ligne 235
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (235,'Rose shocking','FC','0F','C0',252,15,192,'#FC0FC0');
--Ligne 236
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (236,'Rose ultra','FF','6F','FF',255,111,255,'#FF6FFF');
--Ligne 237
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (237,'Rose vif','FF','0','7F',255,0,127,'#FF07F');
--Ligne 238
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (238,'Rouge-orangé sRGB','FF','0','0',255,0,0,'#FF00');
--Ligne 239
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (239,'Rouge anglais (pigment)','F7','23','0C',247,35,12,'#F7230C');
--Ligne 240
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (240,'Rouge cardinal','B8','20','10',184,32,16,'#B82010');
--Ligne 241
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (241,'Rouge cerise','BB','0B','0B',187,11,11,'#BB0B0B');
--Ligne 242
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (242,'Rouge d''alizarine (pigment)','E3','26','36',227,38,54,'#E32636');
--Ligne 243
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (243,'Rouge d''Andrinople (pigment)','A9','11','1',169,17,1,'#A9111');
--Ligne 244
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (244,'Rouge de Falun (pigment)','80','18','18',128,24,24,'#801818');
--Ligne 245
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (245,'Rouge feu','FE','1B','0',254,27,0,'#FE1B0');
--Ligne 246
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (246,'Rouge sang','85','6','6',133,6,6,'#8566');
--Ligne 247
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (247,'Rouge tomette','AE','4A','34',174,74,52,'#AE4A34');
--Ligne 248
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (248,'Rouge turc (pigment)','A9','11','1',169,17,1,'#A9111');
--Ligne 249
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (249,'Rouille','98','57','17',152,87,23,'#985717');
--Ligne 250
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (250,'Roux','AD','4F','9',173,79,9,'#AD4F9');
--Ligne 251
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (251,'Rubis','E0','11','5F',224,17,95,'#E0115F');
--Ligne 252
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (252,'Sable','E0','CD','A9',224,205,169,'#E0CDA9');
--Ligne 253
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (253,'Sable (héraldique)','0','0','0',0,0,0,'#000');
--Ligne 254
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (254,'Safran','F3','D6','17',243,214,23,'#F3D617');
--Ligne 255
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (255,'Safre','1','31','B4',1,49,180,'#131B4');
--Ligne 256
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (256,'Sang de bœuf','73','8','0',115,8,0,'#7380');
--Ligne 257
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (257,'Sanguine','85','6','6',133,6,6,'#8566');
--Ligne 258
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (258,'Saphir','1','31','B4',1,49,180,'#131B4');
--Ligne 259
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (259,'Sarcelle','0','8E','8E',0,142,142,'#08E8E');
--Ligne 260
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (260,'Saumon','F8','8E','55',248,142,85,'#F88E55');
--Ligne 261
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (261,'Saumon rose','FF','91','A4',255,145,164,'#FF91A4');
--Ligne 262
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (262,'Sépia (pigment)','AE','89','64',174,137,100,'#AE8964');
--Ligne 263
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (263,'Sinople (héraldique)','14','94','14',20,148,20,'#149414');
--Ligne 264
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (264,'Smalt (pigment)','0','33','99',0,51,153,'#03399');
--Ligne 265
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (265,'Smaragdin (pigment)','1','D7','58',1,215,88,'#1D758');
--Ligne 266
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (266,'Soufre','FF','FF','6B',255,255,107,'#FFFF6B');
--Ligne 267
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (267,'Souris','9E','9E','9E',158,158,158,'#9E9E9E');
--Ligne 268
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (268,'Tabac','9F','55','1E',159,85,30,'#9F551E');
--Ligne 269
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (269,'Tangerine (couleur)','FF','7F','0',255,127,0,'#FF7F0');
--Ligne 270
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (270,'Taupe','46','3F','32',70,63,50,'#463F32');
--Ligne 271
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (271,'Terre d''ombre (pigment)','92','6D','27',146,109,39,'#926D27');
--Ligne 272
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (272,'Terre de Sienne (pigment)','8A','33','24',138,51,36,'#8A3324');
--Ligne 273
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (273,'Terre de Sienne brûlée (pigment)','E9','74','51',233,116,81,'#E97451');
--Ligne 274
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (274,'Tomate','DE','29','16',222,41,22,'#DE2916');
--Ligne 275
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (275,'Topaze','FA','EA','73',250,234,115,'#FAEA73');
--Ligne 276
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (276,'Tourterelle','BB','AC','AC',187,172,172,'#BBACAC');
--Ligne 277
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (277,'Turquoise','25','FD','E9',37,253,233,'#25FDE9');
--Ligne 278
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (278,'Vanille','E1','CE','9A',225,206,154,'#E1CE9A');
--Ligne 279
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (279,'Vermeil','FF','9','21',255,9,33,'#FF921');
--Ligne 280
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (280,'Vermillon','DB','17','2',219,23,2,'#DB172');
--Ligne 281
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (281,'Vert','0','80','20',0,128,32,'#08020');
--Ligne 282
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (282,'Vert anis','9F','E8','55',159,232,85,'#9FE855');
--Ligne 283
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (283,'Vert bouteille','9','6A','9',9,106,9,'#96A9');
--Ligne 284
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (284,'Vert céladon','83','A6','97',131,166,151,'#83A697');
--Ligne 285
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (285,'Vert chartreuse','C2','F7','32',194,247,50,'#C2F732');
--Ligne 286
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (286,'Vert d''eau','B0','F2','B6',176,242,182,'#B0F2B6');
--Ligne 287
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (287,'Vert de chrome ou anglais (pigment)','18','39','1E',24,57,30,'#18391E');
--Ligne 288
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (288,'Vert-de-gris (pigment)','95','A5','95',149,165,149,'#95A595');
--Ligne 289
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (289,'Vert de Hooker (mélange de pigments)','1B','4F','8',27,79,8,'#1B4F8');
--Ligne 290
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (290,'Vert de vessie (pigment)','22','78','0F',34,120,15,'#22780F');
--Ligne 291
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (291,'Vert épinard','17','57','32',23,87,50,'#175732');
--Ligne 292
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (292,'Vert gazon ou herbe','3A','9D','23',58,157,35,'#3A9D23');
--Ligne 293
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (293,'Vert impérial','0','56','1B',0,86,27,'#0561B');
--Ligne 294
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (294,'Vert kaki','79','89','33',121,137,51,'#798933');
--Ligne 295
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (295,'Vert lichen','85','C1','7E',133,193,126,'#85C17E');
--Ligne 296
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (296,'Vert lime','9E','FD','38',158,253,56,'#9EFD38');
--Ligne 297
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (297,'Vert mélèze','38','6F','48',56,111,72,'#386F48');
--Ligne 298
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (298,'Vert militaire','59','66','43',89,102,67,'#596643');
--Ligne 299
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (299,'Vert mousse','67','9F','5A',103,159,90,'#679F5A');
--Ligne 300
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (300,'Vert opaline','97','DF','C6',151,223,198,'#97DFC6');
--Ligne 301
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (301,'Vert perroquet','3A','F2','4B',58,242,75,'#3AF24B');
--Ligne 302
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (302,'Vert pin','1','79','6F',1,121,111,'#1796F');
--Ligne 303
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (303,'Vert poireau','4C','A6','6B',76,166,107,'#4CA66B');
--Ligne 304
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (304,'Vert pomme','34','C9','24',52,201,36,'#34C924');
--Ligne 305
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (305,'Vert prairie','57','D5','3B',87,213,59,'#57D53B');
--Ligne 306
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (306,'Vert printemps','0','FF','7F',0,255,127,'#0FF7F');
--Ligne 307
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (307,'Vert sapin','9','52','28',9,82,40,'#95228');
--Ligne 308
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (308,'Vert sauge','68','9D','71',104,157,113,'#689D71');
--Ligne 309
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (309,'Vert tilleul','A5','D1','52',165,209,82,'#A5D152');
--Ligne 310
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (310,'Vert Véronèse (pigment)','5A','65','21',90,101,33,'#5A6521');
--Ligne 311
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (311,'Violet','7F','0','FF',127,0,255,'#7F0FF');
--Ligne 312
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (312,'Violet d''évêque','72','3E','64',114,62,100,'#723E64');
--Ligne 313
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (313,'Violine','A1','6','84',161,6,132,'#A1684');
--Ligne 314
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (314,'Viride (pigment)','40','82','6D',64,130,109,'#40826D');
--Ligne 315
INSERT INTO COULEUR (ID_COULEUR, INTITULE_COULEUR, HEXA_ROUGE, HEXA_VERT, HEXA_BLEU, RVB_ROUGE, RVB_VERT, RVB_BLEU, REF_HEXA) VALUES (315,'Zinzolin','6C','2','77',108,2,119,'#6C277');
